// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfrijzddxftftnpegdhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmcmlqemRkeGZ0ZnRucGVnZGhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjMzNTcsImV4cCI6MjA3MjgzOTM1N30.s3h17CvqRJP2R6CScH9uXuZtpEQkh8j5--fNqDBjdiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});